### ISSUE TITLE
Not Issue, but discussion, How are people using this when dealing with code that doesn't understand the abstractions?

### ISSUE THREAD

**Issue by ericnewton76** [System-IO-Abstractions/System.IO.Abstractions#127]
ie, using System.Net.WebClient to download or upload a file from the "mock repository":
- For the DownloadFile operation, the file isn't written to the mock-repo and is written into the physical file system.  
- For the UploadFile operation, the file won't be found since it "lives" only in the mock-repo.

So a general question is, how is the community utilizing System.IO.Abstractions dealing with this problem?

**Comment by manne** [comment]
Can you provide a small example.
The `MockFileStream` should only be used in tests. In the production code the `FileSystem` should be "injected". So in the class you are using the file system, you do not have to care were the files get persisted.

**Comment by jpreese** [comment]
I agree with @manne in this case. Unless there's something we're not quite understanding, your lower level implementations are going to rely on IFileSystem and the top level will inject a new FileSystem -- tests will use the stubbed versions that you inject.

I am closing this ticket though due to inactivity, besides you're an owner of this project now :)
