### ISSUE TITLE
API for TestingHelpers

### ISSUE THREAD

**Issue by manne** [System-IO-Abstractions/System.IO.Abstractions#194]
This issue collects the requirements for an API for `TestingHelpers`, see [here](https://github.com/tathamoddie/System.IO.Abstractions/issues/168#issuecomment-264638699).

- Events #168 
  - Create File
  - Delete File
  - ...
- Handling access (read, write, create) to
  - Drives
    - Disallowed drives #189
  - Files #183 (MockFileStream.StreamType)
  - Directories

Feel free to add further requirements, proposal, ...
It is beneficial to add example and if possible the interfaces.

**Comment by manne** [comment]
cc @Zvirja @AlexanderPruss

**Comment by AlexanderPruss** [comment]
I don't see my submitted Issues as evidence that the TestingHelpers need an API.  It seems clear that the mocked filesystem should function the same way that a non-mocked filesystem does, or what's the point? My issues are just straight-up bugs with relatively simple fixes.

**Comment by MCCoolMoDAue** [comment]
It is a bit misleading that the API of the testing helpers is also used to implement the mock filesystem.
This leaves us with a few problems.
i.e.: We cannot change the TestingHelpers if it changes the behaviour of the mock filesystem.
We are limited in refactoring efforts because we don't want to break existing tests using the Testinghelpers API.
And maybe a few more problems.
The API of used to set up a mock filesystems in our unit tests is almost a side product of the mock filesystem implementation.
Yet necessary.
A separate API could solve some of those issues.
**But I agree, at this point the correctness of the mock filesystem behavior is most important.**

**Comment by manne** [comment]
The correctness of the mock filesystem has top priority for me, too.

Here are some reasons for this discussion for an "API".
Recent PRs introduced lots of new functionality, some with changes on the "API".
For me it is already challenging to verify the functionality of the mock file system regarding to the real file system.
Some changes in the past fixed a small portion, on the other hand it introduced new, incorrect behavior. 
The purpose of this issue is to collect the needed functionality and to prevent uncontrolled growth.

It can be that the "API" is not needed, maybe a change in the development process can solve this challenge. I am open to suggestion and/or solutions.
Especially I do not want to waste the effort of somebody in implementing functionality which is not accepted.

**Comment by AlexanderPruss** [comment]
While I _have_ changed the interface of the MockFileSystem in one of my PRs, I only expanded it, which is hopefully less bad.
