### ISSUE TITLE
Would an abstracted Environment class make sense to be added to System.IO.Abstractions?

### ISSUE THREAD

**Issue by hmemcpy** [System-IO-Abstractions/System.IO.Abstractions#25]
I stumbled upon the need to have a mockable `Environment.CurrentDirectory` property. Quickly looking at its implementation, it's calling `Directory.GetCurrentDirectory()`, which is, unfortunately, not yet implemented in System.IO.Abstractions.

If someone (I) were to write an abstraction for `System.Environment`, would you consider merging it into System.IO.Abstractions? (it doesn't _really_ belong to IO, but it uses several things from System.IO directly).

**Comment by ericnewton76** [comment]
Its a tough one, but theoretically you wouldn't want to start going down this rabbit hole, as @tathamoddie suggests.

We need a better campaign to convince Microsoft to start including dependency injection libraries like System.IO.Abstractions into the core framework so that all that "other" code could be testable too.

With the framework going into "Open Source Mode", I'm wondering if the core BCL team at Microsoft could seriously start to consider phasing out things like Environment.CurrentDirectory in favor of more testable implementations

**Comment by ericnewton76** [comment]
Of note, when looking at a C# library for VHDs, I realized that IFileSystem abstraction is SOOOO important... because theoretically your FileSystem could be repointed to a VHD with an undo disk, thereby simulating mmmmmmmmmmuch more situations being called for here in issues for MockFileSystem (like Readonly and out-of-space conditions).  Or even an IFileSystem implementation that "clones" the current system, where you could test interactions with existing structure while isolating and abstracting the test-library changes from that filesystem.

@tathamoddie you may see me send over some pull requests related to that type of work, expanding IFileSystem a bit to provide support for the C# library for VHDs, ISOs, etc... basically "filesystems in a box" of sorts...

**Comment by manne** [comment]
there is already a discussion dotnet/corefx#312

**Comment by fgreinacher** [comment]
I understand the motivation for this, but the purpose of this library is to provide abstractions for file system operations. Everyone is free to start something like `System.Abstractions` as a separate library 👍 

@tathamoddie @jpreese I'd suggest to close this.

**Comment by jpreese** [comment]
I agree that it's not the responsibility of this library to include System.Environment.

**Comment by jeffkl** [comment]
I've created a library for abstracting away environment variable operations for `System.Environment` if anyone finds it useful.

https://github.com/jeffkl/EnvironmentAbstractions
