### ISSUE TITLE
Project roadmap

### ISSUE THREAD

**Issue by fgreinacher** [System-IO-Abstractions/System.IO.Abstractions#287]
Looking at the commit history and issue/PR states it seems like this project is kinda dead at the moment.

I really love this library and am wondering if there is any similar (drop-in) thing I should switch to. 

If there is nothing should we try to find a new home for this project?

@tathamoddie

**Comment by nathan-boyd** [comment]
I share the same sentiment, and I'm interested in helping with long term support for this project or a fork if that's the direction we have to go.

**Comment by ericnewton76** [comment]
At a certain point, a library that is just the interfaces for a BCL will not need new commits unless the BCL library changes in some way. 

I wouldn’t say it’s dead, I would say it’s complete, for the time being. Don’t have to constantly be in flux do we?

**Comment by fgreinacher** [comment]
I’d agree if there wouldn’t be 58 open issues and 37 open PRs. There is a lot to improve, especially for proper x-plat support. I’d be totally willing to support here if that is feasible.

**Comment by nathan-boyd** [comment]
cross platform support is my major driver as well, and like @fgreinacher i would love to help keep the project going. if the owner is open to creating / expanding the maintainers groups i would love to join.

**Comment by fgreinacher** [comment]
Tagging @colin-young and @jpreese as you also seem to have contributor rights here (at least your names were mentioned in #229 🤣

**Comment by jpreese** [comment]
Hey guys, thanks for the ping. I've reached out to @tathamoddie to see if we can get some additional help around this. 

When I hear back, I'll get with some of the names I see here and discuss how we would like to move forward. I would love to get some more contributors, and build a community around this project again.

**Comment by jpreese** [comment]
As an update, I just got word @tathamoddie is traveling and most likely will not be completely available until the 10th of July.

**Comment by tathamoddie** [comment]
Hi folks 👋

Sorry I've been so distant on this one. Over the last couple of years I've drifted a long way from touching a compiler. I'm clearly not in a good position to maintain this repo.

Until about 2 mins ago, I was the repo owner, and @jpreese, @colin-young, and @manne had contributor rights. Because the repo was under my personal account, not an org, I couldn't expand out to co-owners or anything. I've just moved it all from `github.com/tathamoddie/System.IO.Abstractions` to `github.com/System-IO-Abstractions/System.IO.Abstractions`, and sent @jpreese an invite to be an admin of it (based on previous engagement, email threads from him, and his work context). I'll need to work out how to share access to the AppVeyor build.

**Comment by tathamoddie** [comment]
Per #290, I've updated paths in the package to point to the new org-based repo

I've setup the AppVeyor project (https://ci.appveyor.com/project/tathamoddie/system-io-abstractions) to be manageable by anybody in the https://github.com/orgs/System-IO-Abstractions/teams/owners team

**Comment by jpreese** [comment]
All set, thanks! 🎉

**Comment by fgreinacher** [comment]
That sounds like a great plan. Thanks everyone for taking care!

**Comment by jpreese** [comment]
@fgreinacher and @nathan-boyd if you were interested in being collaborators could you respond here? @tathamoddie has gone through and switched us over to an org which means I can onboard a couple volunteers.

**Comment by fgreinacher** [comment]
I definitely would like to help!
