### ISSUE TITLE
Encrypt/Decrypt inconsistent with .NET Framework

### ISSUE THREAD

**Issue by hangy** [System-IO-Abstractions/System.IO.Abstractions#304]
The behaviour of the mock `File.Encrypt` is inconsistent with the actual file system's behaviour on .NET 4.

.NET sets the encrypted attribute in NTFS, which encrypts the file. Thus, reading the file content after encrypting it transparently decrypts the content.
```
> var fs = new FileSystem();
> fs.File.WriteAllText(@"D:\test.txt", "foo");
> fs.File.ReadAllText(@"D:\test.txt")
"foo"
> fs.File.Encrypt(@"D:\test.txt")
> fs.File.ReadAllText(@"D:\test.txt")
"hi"
```

The mock currently performs an XOR on the content bytes, so that we cannot read the file's content
```
> var mfs = new MockFileSystem();
> mfs.AddFile(@"D:\test.txt", new MockFileData("bar"));
> mfs.File.ReadAllText(@"D:\test.txt")
"bar"
> mfs.File.Encrypt(@"D:\test.txt")
> mfs.File.ReadAllText(@"D:\test.txt")
"b`p"
```

I believe the only observable change (from the .NET app's point of view) should be the added `Encrypted` attribute.

**Comment by jpreese** [comment]
Thanks for bringing this up @hangy. 

I'm pretty sure I agree with you. I've looked through the documentation and did some local tests myself, and I'm not really seeing any way to see the contents of the encrypted file. ReadAllText, ReadAllByes, etc definitely shows you the true contents. I don't even think you'd leverage the encrypted text in production or test code as it's going to differ from machine to machine anyway.

This feature originated in #98, so quite old. But not seeing any discussion there as to why the XOR approach was taken.

Since it is removing functionality, I'd like to double check with @tathamoddie if there are any gotchas, but I think this is OK.

**Comment by hangy** [comment]
When encrypting files, the .NET Framework just sets some NTFS attributes, which causes the OS to transparently encrypt the file. You can open the encrypted file with notepad without any issues. IMHO, this is a bugfix, because testing with encrypted files is not possible right now. 😉
