### ISSUE TITLE
Calling File.Create(@"C:\foo.ifc") fails in latest version

### ISSUE THREAD

**Issue by PhilipDaniels** [System-IO-Abstractions/System.IO.Abstractions#310]
Throws exception 

```
System.IO.DirectoryNotFoundException: 'Could not find a part of the path 'C:\foo.ifc'.'
```

Just updated from version 178 to 198 and this error has appeared in a test project. The actual project ref is

```
<PackageReference Include="System.IO.Abstractions.TestingHelpers" Version="2.1.0.198" />
```

but this does imply System.IO.Abstractions v 2.1.0.198.

**Comment by jpreese** [comment]
@PhilipDaniels this is more than likely an intended change (PR #286).

Assuming you're trying something along the following:
```csharp
var fs = new MockFileSystem();
fs.File.Create(@"C:\foo.ifc")
```

This would throw a DirectoryNotFoundException because C:\ does not exist. This is similar behavior you would see in System.IO.File.Create

```csharp
System.IO.File.Create(@"K:\foo.ifc"); // assuming you don't have a K drive
```

If this is not the use case that you are experiencing this issue with, please let me know!

**Comment by PhilipDaniels** [comment]
Quick response! Yes, that is exactly what is happening. I am sympathetic to making the mock file system more accurately mimic reality, it was just a bit of a surprise to have a minor version bump suddenly fail some tests that have been OK for 2 years :-) Luckily the following both work

```
fileSystem.Directory.CreateDirectory(@"C:\");
fileSystem.Directory.CreateDirectory(@"C:\a\b\c\d");
```

So it is not too onerous to ensure that directories get created in the tests.
