### ISSUE TITLE
Include System.IO's StreamReader and StreamWriter into System.IO.Abstractions

### ISSUE THREAD

**Issue by sharpSteff** [System-IO-Abstractions/System.IO.Abstractions#392]
In our application we need a lot of System.IO.StreamWriters and System.IO.StreamReaders for data and logs in csv format beside the typical File-and Directory-Operations.  

Therefore I like to include these classes into System.IO.Abstractions to be able to create UnitTests for our businesslogic.

The abstration layer should have every available streamwriter/reader-constructor in a [StreamWriterFactory](https://github.com/System-IO-Abstractions/System.IO.Abstractions/pull/383/files#diff-a948ef39bc706277314b324d18cb27da):

```
IStreamWriter FromPath(string path);
IStreamWriter FromPath(string path, bool append);
IStreamWriter FromPath(string path, bool append, Encoding encoding);
IStreamWriter FromPath(string path, bool append, Encoding encoding, int bufferSize);
IStreamWriter FromStream(Stream stream);
IStreamWriter FromStream(Stream stream, Encoding encoding);
IStreamWriter FromStream(Stream stream, Encoding encoding, int bufferSize);

```

The StreamWriter/ReaderWrapper-Class should use the FIleStreamWrapper-Class inside to reduce redundant code.

The pullrequest #383 shows a possible implemention of the StreamWriter-Abstractionlayer

**Comment by herebebeasties** [comment]
I've commented on the PR itself, but perhaps this issue is the more appropriate place for discussion of the whole concept. Why do you want to have an `IStreamWriter` interface? `IFileSystem` already lets you mock out the underlying actual storage (obviously) and it's really not clear to me what you gain from mocking the writer itself.

Specifically, any `IStreamWriter` implementation is going to end up quite complicated, in that it inherits from `TextWriter`, complete with all the `Write()` overloads for objects, primitive types, etc. I really wouldn't want to be mocking all that out as an interface in any tests I wrote for code that heavily interacted with StreamWriter, for fear of not actually testing the code properly. (Will your mock behaviour actually reflect reality? Why would you bother mocking it when you can use a real one which doesn't do actual I/O? etc.)

These methods are all virtual, too. So if you wanted to get something like FakeItEasy to mock a `TextWriter` and stub out some of the methods you can do that anyway, without any of this extra machinery.

So I really don't understand what benefit this gives you. Do you have an example of a concrete use case that can't really be achieved elegantly any other way?

**Comment by sharpSteff** [comment]
> IFileSystem already lets you mock out the underlying actual storage (obviously) and it's really not clear to me what you gain from mocking the writer itself.

With mocking the StreamWriter. You will obviously save lines of code and don't have to take care of streams by yourself.  Of course this is a lot of code just wrapping the streamwriter, but at the end these are additional Features, which will help the users.

> Why do you want to have an IStreamWriter interface?
You may be right. A base class would be enough. However when you look into the dotNet [TextWriter](https://github.com/dotnet/corefx/blob/master/src/Common/src/CoreLib/System/IO/TextWriter.cs), you will find a lot of empty virtual methods.

**Comment by fgreinacher** [comment]
I still don't understand what problem(s) these new methods solve that cannot be solved via `FileBase.OpenText` or `FileBase.CreateText`. Can you elaborate a bit on this @sharpSteff?

**Comment by fgreinacher** [comment]
Closing this for the reasons mentioned in #383.
