### ISSUE TITLE
Where is File.WriteAllBytesAsync and other *Async?

### ISSUE THREAD

**Issue by mifopen** [System-IO-Abstractions/System.IO.Abstractions#441]
I see that they are only in .net core, but how can I work with them anyway?

**Comment by mifopen** [comment]
I have just used FileStream and that is OK

**Comment by ajbeaven** [comment]
Please reopen this. It would be helpful for this library to match the public API of System.IO.File.

**Comment by fgreinacher** [comment]
Reopened, this is a legit enhancement

**Comment by iron9light** [comment]
I'm looking at a common IO/FileSystem abstraction layer for both local/remote/cloud.
For the cloud, I mean Azure Storage Blobs, etc.
To support those scenarios, I think your lib should add async ops support.
Even for something "like list all children of a directory" or "check if one File/Directory is exsited" may be async.
Since in cloud scenario, every action should be async by default.

**Comment by fgreinacher** [comment]
Sorry to say, but the purpose of this library is to provide a drop-in replacement for System.IO APIs, so adding additional functionality is out-of-scope here. Of course feel free to create your own library on top of, instead of within SIOA.

**Comment by iron9light** [comment]
@fgreinacher Got it. And nice work anyway.
I just wondering if an .NET port for [java nio2 file](https://docs.oracle.com/javase/tutorial/essential/io/fileio.html) or [hadoop filesystem](https://github.com/apache/hadoop/tree/trunk/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs) will be really useful.
Since System.IO is a really bad design.

**Comment by fgreinacher** [comment]
Starting with v6.0.1 we provide a .NET Core target 🎉
