### ISSUE TITLE
Can't return FileInfo

### ISSUE THREAD

**Issue by Loreno10** [System-IO-Abstractions/System.IO.Abstractions#494]
I had a method:
```csharp
public ICollection<FileInfo> GetFiles(string directoryPath)
{
    var directoryInfo = new DirectoryInfo(directoryPath);
    return directoryInfo.GetFiles();
}
```

To make it testable, I changed it to:
```csharp
public IEnumerable<FileInfo> GetFiles(string directoryPath)
{
    var directoryInfo = _fileSystem.DirectoryInfo.FromDirectoryName(directoryPath);
    return directoryInfo.GetFiles();
}
```

However, this doesn't compile, because now the last line returns collection of `IFileInfo` instead of `FileInfo`. How do I return FileInfo?

**Comment by JerrettDavis** [comment]
Any reason you can't return `IFileInfo` instead of `FileInfo`?

**Comment by Loreno10** [comment]
Well, my application started to crash for some reason when I was returning IFileInfo. I'll have to investigate why.

**Comment by JerrettDavis** [comment]
From what I can gather from the repository, there's nothing currently built in. The `FileInfoWrapper` class is capable of converting a `FileInfo` instance into a `IFileInfo` instance, but not the other way around. It should be somewhat trivial to build your own mapping if necessary. However, it'd likely be considerably more beneficial to embrace the abstractions completely and simply pass the abstractions from the `System.IO.Abstractions`  library around instead of the concrete implementations from `System.IO`.

`FileInfoBase` does keep the original `FileInfo` object around under the hood. In theory, you could extend it to return the `FileInfo` instance, but I'd personally caution against it.

**Comment by Loreno10** [comment]
I am using IFileInfo everywhere now and it works. Thanks
