### ISSUE TITLE
System.IO.Abstractions.TestingHelpers has not been released for 11.0.10

### ISSUE THREAD

**Issue by Mobrockers** [System-IO-Abstractions/System.IO.Abstractions#609]
**Describe the bug**
We use a variable in Directory.Build.props to keep the versions of System.IO.Abstractions.TestingHelpers and System.IO.Abstractions in sync. This has worked fine so far but 11.0.10 has been released only for System.IO.Abstractions and not for the TestingHelpers. This blocks us from updating. Is this intended? We kinda rely on the version numbers to be the same at the moment, if intended we need to find a different solution.

**Comment by fgreinacher** [comment]
No, that's not intended, seems like NuGet.org had some problems yesterday (see https://ci.appveyor.com/project/tathamoddie/system-io-abstractions/branch/master/job/nysguy98gjt11v7o). I'll retry the push

**Comment by garyhuntddn** [comment]
Looks to be related to not being able to push the symbols for the System.IO.Abstractions rather than anything to do with the TestingHelpers (you've probably seen that in the logs too).

As a temporary thing we're going to grab the nuget packages from here... https://ci.appveyor.com/project/tathamoddie/system-io-abstractions/builds/33572886/job/3waytne22awl5780/artifacts

**Comment by fgreinacher** [comment]
That's really weird. No idea whether the problem is at the AppVeyor our NuGet.org side. Sent out a [query via Twitter](https://twitter.com/fgreinacher/status/1273314597584416768).

As a workaround I'll disable symbol publishing (https://github.com/System-IO-Abstractions/System.IO.Abstractions/pull/611).

**Comment by fgreinacher** [comment]
This is fixed in `11.0.12` (might need a few minutes to be available on NuGet.org)

**Comment by fgreinacher** [comment]
Starting with `11.0.15` symbols are published again (using the modern `snupkg` format).
